version: '3'
services:
  # https://www.docker.com/blog/deploying-web-applications-quicker-and-easier-with-caddy-2/
  caddy:
    image: caddy
    ports:
      - '80:80'
      - '443:443'
    networks:
      - caddy-net
    volumes:
      - ./caddy/data/:/data/
      - ./caddy/config/:/config/
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile

  blog:
    image: ghcr.io/yeolyi/blog:latest
    ports:
      - '3000:3000'
    networks:
      - caddy-net

networks:
  caddy-net:
