export const order = [
  'setup',
  'trigger-schedule-render-commit',
  'react-dom-is-simple',
  'initial-trigger',
  'fiber-traverse',
  'perform-unit-of-work',
  'begin-work-host-root',
  'begin-work-app',
  'complete-work',
  'initial-commit',
  'rerender-trigger',
  'rerender-reuse',
  'compare-props',
  'child-always-rerenders',
  'rerender-fiber',
  'hook-dispatcher',
];
