import type { Metadata } from "next";
import { IBM_Plex_Sans_KR } from "next/font/google";
import Header from "./components/Header";
import "@pigment-css/react/styles.css";

const ibmPlexSans = IBM_Plex_Sans_KR({
  variable: "--font-ibm-plex-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ibmPlexSans.variable}`}
        style={{ fontFamily: "var(--font-ibm-plex-sans)" }}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
