name: Build and deploy blog

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.0

      - name: Log in to the Container Registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Checkout blog_nextjs
        uses: actions/checkout@v3
        with:
          repository: yeolyi/blog_nextjs

      - name: SCP Command to Transfer Files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          source: "docker-compose.yml"
          target: "blog"
          overwrite: true

      - name: SCP Command to Transfer Files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          source: "Caddyfile"
          target: "blog/caddy"
          overwrite: true

      - name: Build and push Docker images
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          tags: ghcr.io/yeolyi/blog:latest

      - name: Deploy Docker Image via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}

          script: |
            cd ~/blog
            docker-compose down
            docker-compose pull
            docker-compose up -d
