name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: SCP Command to Transfer Files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          source: "docker-compose.yml,data/nginx/app.config"
          target: "blog_nextjs"
          overwrite: true

      - name: Build and push Docker images
        uses: docker/build-push-action@v4.1.1
        with:
          push: true
          tags: yeolyi1310/blog-nextjs

      - name: Deploy Docker Image via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}

          script: |
            cd ~/blog-nextjs
            docker-compose down
            docker-compose pull
            docker-compose up -d
